# Generated by Django 6.0.1 on 2026-04-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numero_siret',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Numéro SIRET'),
        ),
    ]
