# Generated by Django 6.0.1 on 2026-01-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='companies.company', verbose_name='Entreprise affiliée'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('personal', 'Client'), ('business', 'Propriétaire'), ('coach', 'Coach')], default='personal', max_length=20, verbose_name="Rôle de l'utilisateur"),
        ),
    ]
