# Generated by Django 6.0.1 on 2026-01-29 16:45

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_company_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferences',
            field=models.JSONField(blank=True, default=users.models.get_default_preferences),
        ),
    ]
