# Generated by Django 6.0.1 on 2026-01-31 13:38

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.RandomFileName('avatars/')),
        ),
    ]
