# Generated by Django 6.0.1 on 2026-02-02 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'activité")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Catégorie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/', verbose_name="Image de l'activité")),
                ('location_address', models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse spécifique de l'activité")),
                ('start_time', models.DateTimeField(verbose_name='Date et heure de début')),
                ('duration', models.DurationField(verbose_name='Durée (ex: 1h30min)')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Nombre maximum de participants')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('level', models.CharField(choices=[('all', 'Tous niveaux'), ('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='all', max_length=20, verbose_name='Niveau requis')),
                ('venue', models.CharField(choices=[('indoor', 'Intérieur'), ('outdoor', 'Extérieur')], default='indoor', max_length=10, verbose_name='Lieu (Intérieur/Extérieur)')),
                ('is_public', models.BooleanField(default=True, help_text="Décocher pour masquer l'activité du site public.", verbose_name='Publique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='companies.company', verbose_name='Entreprise organisatrice')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'type': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_activities', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (sur 5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='activities.activity', verbose_name='Activité')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Note d'activité",
                'verbose_name_plural': "Notes d'activités",
                'unique_together': {('activity', 'user')},
            },
        ),
    ]
