# Generated by Django 6.0.1 on 2026-01-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse spécifique de l'activité"),
        ),
    ]
