# Generated by Django 6.0.1 on 2026-02-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sport_zen',
            field=models.BooleanField(default=False, help_text="Cocher si l'activité est accessible, non-compétitive et bienveillante.", verbose_name='Label SportZen'),
        ),
    ]
