# Generated by Django 6.0.1 on 2026-01-31 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activityrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrating',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (sur 5)'),
        ),
    ]
