"""
Django settings for Sportradar_Backend_v2 project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-une-cle-locale-par-defaut')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

 # Importer le paquet

# ...

# Détecter si on est en production sur Render
# Render définit automatiquement la variable d'environnement RENDER
IS_PRODUCTION = 'RENDER' in os.environ

if IS_PRODUCTION:
    # En production, utiliser la base de données PostgreSQL de Render
    DATABASES = {
        'default': dj_database_url.config(
            # L'URL est récupérée depuis la variable d'environnement DATABASE_URL
            conn_max_age=600,
            ssl_require=True # Forcer la connexion sécurisée
        )
    }
else:
    # En développement (local), continuer à utiliser SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # Apps tierces
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'corsheaders',
    'weather',

    # Nos applications
    'users.apps.UsersConfig',
    'companies.apps.CompaniesConfig',
    'activities.apps.ActivitiesConfig',
    'bookings.apps.BookingsConfig',



]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'Sportradar_Backend_v2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# --- Jazzmin (inchangé) ---
JAZZMIN_SETTINGS = {
    'site_title': 'SportRadar Admin',
    'welcome_sign': 'Bienvenue dans SportRadar',
    'show_sidebar': True,
    'navigation_expanded': True,
}

WSGI_APPLICATION = 'Sportradar_Backend_v2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles' )

# --- Modèle d'Authentification Personnalisé ---
# On dit à Django d'utiliser notre classe CustomUser de l'application users
# pour gérer tout ce qui concerne les utilisateurs.
AUTH_USER_MODEL = 'users.CustomUser'

# --- Django REST Framework ---
# --- Django REST Framework ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # ← AJOUTE CETTE LIGNE
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# --- AJOUTEZ CETTE NOUVELLE CONFIGURATION ---
SPECTACULAR_SETTINGS = {
    'TITLE': 'SportRadar API',
    'DESCRIPTION': 'API pour le projet SportRadar',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
# À la fin du fichier
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # L'adresse de votre front-end React
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "https://sportradar-front.onrender.com/"
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "https://sportradar-front.onrender.com/"
]

# ✅ CORRIGÉ : Configuration JWT cohérente
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # Token d'accès : 15 minutes (sécurisé)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),    # Token de rafraîchissement : 7 jours
    # Le refresh token doit TOUJOURS avoir une durée de vie plus longue que l'access token
}

# ✅ CORRIGÉ : Configuration MEDIA sécurisée
MEDIA_URL = '/media/'  # Préfixe pour les URLs des fichiers médias
MEDIA_ROOT = BASE_DIR / 'media'  # Dossier séparé pour les fichiers téléversés



# Les autres variables (AWS, OPENWEATHER, etc.) seront lues depuis le .env si elles existent, sinon ignorées.
OPENWEATHER_API_KEY = os.getenv('OPENWEATHER_API_KEY')
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME')