"""
Django settings for Sportradar_Backend_v2 project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4*t6ompn80j49jnfple^6=(4%h2!@ob7ccjkjvfffz16qh9t-2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # Apps tierces
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'corsheaders',
    'weather',

    # Nos applications
    'users.apps.UsersConfig',
    'companies.apps.CompaniesConfig',
    'activities.apps.ActivitiesConfig',
    'bookings.apps.BookingsConfig',



]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'Sportradar_Backend_v2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# --- Jazzmin (inchangé) ---
JAZZMIN_SETTINGS = {
    'site_title': 'SportRadar Admin',
    'welcome_sign': 'Bienvenue dans SportRadar',
    'show_sidebar': True,
    'navigation_expanded': True,
}

WSGI_APPLICATION = 'Sportradar_Backend_v2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- Modèle d'Authentification Personnalisé ---
# On dit à Django d'utiliser notre classe CustomUser de l'application users
# pour gérer tout ce qui concerne les utilisateurs.
AUTH_USER_MODEL = 'users.CustomUser'

# --- Django REST Framework ---
# --- Django REST Framework ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # ← AJOUTE CETTE LIGNE
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# --- AJOUTEZ CETTE NOUVELLE CONFIGURATION ---
SPECTACULAR_SETTINGS = {
    'TITLE': 'SportRadar API',
    'DESCRIPTION': 'API pour le projet SportRadar',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
# À la fin du fichier
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # L'adresse de votre front-end React
    "http://127.0.0.1:3000",
    "http://localhost:5173"
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
]

# ✅ CORRIGÉ : Configuration JWT cohérente
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # Token d'accès : 15 minutes (sécurisé)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),    # Token de rafraîchissement : 7 jours
    # Le refresh token doit TOUJOURS avoir une durée de vie plus longue que l'access token
}

# ✅ CORRIGÉ : Configuration MEDIA sécurisée
MEDIA_URL = '/media/'  # Préfixe pour les URLs des fichiers médias
MEDIA_ROOT = BASE_DIR / 'media'  # Dossier séparé pour les fichiers téléversés