# Generated by Django 6.0.1 on 2026-02-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='Code Postal')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('website', models.URLField(blank=True, verbose_name='Site Web')),
                ('sport_zen', models.BooleanField(default=False, help_text="Cocher si l'entreprise propose des activités accessibles, non-compétitives et bienveillantes.", verbose_name='Label SportZen')),
                ('is_verified', models.BooleanField(default=False, help_text="Cocher si le profil de l'entreprise a été vérifié par un administrateur.", verbose_name='Vérifiée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
    ]

