# Generated by Django 6.0.1 on 2026-02-02 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='confirmed', max_length=20, verbose_name='Statut')),
                ('booking_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='activities.activity', verbose_name='Activité réservée')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_attendee', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-booking_time'],
                'unique_together': {('activity', 'attendee')},
            },
        ),
    ]
