# Generated by Django 6.0.1 on 2026-03-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nb_persone',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de places réservées par cet utilisateur', verbose_name='Nombre de participants'),
        ),
    ]
