# Generated by Django 6.0.1 on 2026-04-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_nb_persone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nb_persone',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de participants'),
        ),
    ]
